from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from app.tools.audit_log import append_audit_event
from app.tools.auto_scientist.contracts import (
    LATEST_RUN_JSON,
    REPORT_MD,
    SAFETY_LIMITATIONS,
    SCHEMA_PREFIX,
    utc_now,
    write_project_json,
    write_project_text,
)
from app.tools.manuscript_safety import check_manuscript_safety

AUTONOMOUS_PAPER_MD = "manuscript/auto_scientist_paper.md"
AUTONOMOUS_PAPER_TEX = "manuscript/auto_scientist_paper.tex"
AUTONOMOUS_PAPER_AUDIT_JSON = "auto_scientist/paper_audit.json"
AUTONOMOUS_PAPER_NOTICE = (
    "AI-generated Auto Scientist manuscript from local registered experiment templates. "
    "Requires human review before external use."
)


def _latex_escape(text: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def _markdown_to_latex(markdown: str) -> str:
    lines: list[str] = []
    for raw in markdown.splitlines():
        line = raw.strip()
        if not line:
            lines.append("")
            continue
        if line.startswith("# "):
            lines.append(r"\section{" + _latex_escape(line[2:].strip()) + "}")
            continue
        if line.startswith("## "):
            lines.append(r"\subsection{" + _latex_escape(line[3:].strip()) + "}")
            continue
        if line.startswith("- "):
            lines.append(r"\begin{itemize}\item " + _latex_escape(line[2:].strip()) + r"\end{itemize}")
            continue
        if line.startswith(">"):
            lines.append(r"\begin{quote}" + _latex_escape(line.lstrip("> ")) + r"\end{quote}")
            continue
        lines.append(_latex_escape(line))
    return "\n\n".join(lines)


def _metric_lines(results: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for item in results:
        result = item.get("result") if isinstance(item.get("result"), dict) else {}
        metrics = result.get("metrics") if isinstance(result, dict) else {}
        metric_keys = ", ".join(sorted(metrics.keys())) if isinstance(metrics, dict) else "none"
        outputs = ", ".join(item.get("output_files", [])) or "none"
        lines.append(
            f"- `{item.get('experiment_id')}` used template `{item.get('template_name')}`; "
            f"status `{item.get('status')}`; metric groups: {metric_keys}; outputs: {outputs}."
        )
    return lines or ["- No registered experiment results were available for this draft."]


def _claim_lines(results: list[dict[str, Any]]) -> list[str]:
    lines: list[str] = []
    for item in results:
        result = item.get("result") if isinstance(item.get("result"), dict) else {}
        claims = result.get("claims") if isinstance(result, dict) else []
        for claim in claims if isinstance(claims, list) else []:
            if not isinstance(claim, dict):
                continue
            lines.append(
                f"- `{claim.get('support_status', 'needs_human_review')}`: {claim.get('claim', '')}"
            )
    return lines or ["- No result-level claims were generated; keep findings as limitations."]


def generate_auto_scientist_paper(
    project_dir: Path,
    project_id: str,
    run_id: str,
    ideas_payload: dict[str, Any],
    experiment_plan: dict[str, Any],
    results: list[dict[str, Any]],
    analysis: dict[str, Any],
    paper_outputs: dict[str, Any] | None = None,
    experiment_tree: dict[str, Any] | None = None,
) -> dict[str, Any]:
    topic = ideas_payload.get("topic") or "local research project"
    question = ideas_payload.get("research_question") or "What can the local evidence support?"
    support_counts = analysis.get("claim_support_counts", {}) if isinstance(analysis, dict) else {}
    status_counts = analysis.get("status_counts", {}) if isinstance(analysis, dict) else {}
    selected_tree_node = (experiment_tree or {}).get("selected_best_node") if isinstance(experiment_tree, dict) else None
    heuristic_best_node = (experiment_tree or {}).get("best_node") if isinstance(experiment_tree, dict) else None
    emphasized_node = selected_tree_node if isinstance(selected_tree_node, dict) else heuristic_best_node if isinstance(heuristic_best_node, dict) else {}
    title = f"Safe Local Auto Scientist Study of {topic}"
    markdown_lines = [
        f"# {title}",
        "",
        f"> {AUTONOMOUS_PAPER_NOTICE}",
        "",
        "## Abstract",
        "",
        (
            f"This manuscript is generated by a safe local Auto Scientist loop for the question: {question} "
            "The loop generates ideas, runs registered local experiment templates, analyzes outputs, writes a draft, "
            "and invokes an internal reviewer. It is a development artifact and requires human scientific review."
        ),
        "",
        "## Introduction",
        "",
        (
            f"The topic is {topic}. The purpose of this run is to test whether project-local literature, data, and audit artifacts "
            "can support a cautious research draft without relying on external services or arbitrary generated code execution."
        ),
        "",
        "## Idea Generation",
        "",
    ]
    for idea in ideas_payload.get("ideas", []):
        if isinstance(idea, dict):
            markdown_lines.append(f"- `{idea.get('idea_id')}`: {idea.get('title')} — {idea.get('rationale')}")
    markdown_lines.extend(
        [
            "",
            "## Experiment Plan",
            "",
            (
                "The experiment plan was restricted to registered local templates. "
                f"Planned experiments: {len(experiment_plan.get('experiments', []))}. "
                "Arbitrary generated code execution was disabled."
            ),
            "",
            "## Methods",
            "",
            (
                "The system executed safe local templates over project artifacts, including evidence inventory, retrieval evaluation, "
                "claim audit evaluation, descriptive data profiling, and writing safety checks when selected. These templates produce "
                "structured JSON, Markdown summaries, and optional SVG figures under `auto_scientist/experiments/`."
            ),
            "",
            "## Results",
            "",
            f"Experiment status counts: `{status_counts}`.",
            "",
            *_metric_lines(results),
            "",
            "## Experiment Tree Best Candidate",
            "",
            (
                f"Tree search best node for manuscript emphasis: `{emphasized_node.get('node_id', 'not_available')}`. "
                f"Template: `{emphasized_node.get('template_name', 'not_available')}`; "
                f"score: `{emphasized_node.get('score', 'not_available')}`. "
                "This selection is a local heuristic or human workflow choice, not scientific proof."
                if experiment_tree
                else "Experiment tree search was not enabled for this run."
            ),
            "",
            (
                f"Human-selected node reason: {(experiment_tree or {}).get('selected_reason') or 'not provided'}."
                if experiment_tree and (experiment_tree or {}).get('selected_best_node_id')
                else "No human-selected experiment tree node was recorded."
            ),
            "",
            (
                f"Best-node selection rationale: {emphasized_node.get('selection_rationale', 'not available')}"
                if experiment_tree
                else "Best-node selection rationale was not generated because experiment tree search was disabled."
            ),
            "",
            "## Evidence-Bound Claims",
            "",
            f"Claim support counts from local result artifacts: `{support_counts}`.",
            "",
            *_claim_lines(results),
            "",
            "## Internal Review and Revision Needs",
            "",
            (
                "The generated paper must be checked against `auto_scientist/scientist_review.json`, "
                "`provenance/claim_audit.json`, and human review decisions before any external use."
            ),
            "",
            "## Limitations",
            "",
            *[f"- {item}" for item in SAFETY_LIMITATIONS],
            "- This manuscript is not peer review, publication readiness, or scientific proof.",
            "- Any generated references remain placeholders until manually verified.",
            "",
            "## Related Draft Artifacts",
            "",
        ]
    )
    if paper_outputs:
        for key, value in paper_outputs.items():
            if value:
                markdown_lines.append(f"- {key}: `{value}`")
    markdown_lines.extend(
        [
            "",
            "## References",
            "",
            "- Placeholder references only; generate BibTeX and approve references before external use.",
        ]
    )
    markdown = "\n".join(str(line) for line in markdown_lines) + "\n"
    safety = check_manuscript_safety(markdown)
    # The safety checker allows negated terms in most sentences, but keep the audit visible.
    write_project_text(project_dir, AUTONOMOUS_PAPER_MD, markdown)
    latex_body = _markdown_to_latex(markdown)
    latex = "\n".join(
        [
            r"\documentclass[11pt]{article}",
            r"\usepackage[margin=1in]{geometry}",
            r"\usepackage{hyperref}",
            r"\author{ResearchAgent Auto Scientist}",
            r"\date{Local draft generated from registered experiment templates}",
            r"\begin{document}",
            r"\title{" + _latex_escape(title) + "}",
            r"\maketitle",
            latex_body,
            r"\end{document}",
            "",
        ]
    )
    write_project_text(project_dir, AUTONOMOUS_PAPER_TEX, latex)
    audit = {
        "schema_version": f"{SCHEMA_PREFIX}.autonomous_paper_audit.v1",
        "project_id": project_id,
        "run_id": run_id,
        "created_at": utc_now(),
        "paper_file": AUTONOMOUS_PAPER_MD,
        "experiment_tree_file": "auto_scientist/experiment_tree.json" if experiment_tree else None,
        "experiment_tree_best_node": (experiment_tree or {}).get("best_node") if experiment_tree else None,
        "experiment_tree_selected_best_node": (experiment_tree or {}).get("selected_best_node") if experiment_tree else None,
        "latex_file": AUTONOMOUS_PAPER_TEX,
        "report_file": REPORT_MD,
        "latest_run_file": LATEST_RUN_JSON,
        "safety": safety,
        "human_review_required": True,
        "arbitrary_code_execution": False,
        "limitations": SAFETY_LIMITATIONS,
    }
    write_project_json(project_dir, AUTONOMOUS_PAPER_AUDIT_JSON, audit)
    append_audit_event(
        project_dir,
        project_id,
        "generate_auto_scientist_paper",
        "Auto Scientist generated a full local manuscript draft from experiment outputs.",
        {
            "run_id": run_id,
            "paper_file": AUTONOMOUS_PAPER_MD,
        "experiment_tree_file": "auto_scientist/experiment_tree.json" if experiment_tree else None,
        "experiment_tree_best_node": (experiment_tree or {}).get("best_node") if experiment_tree else None,
            "latex_file": AUTONOMOUS_PAPER_TEX,
            "human_review_required": True,
        },
        source="api",
        event_category="agent",
        risk_level="medium",
        entity_type="auto_scientist",
        entity_id=run_id,
    )
    return audit
